### ISSUE TITLE
[CSS] V10 Journals sidebar background is transparent

### ISSUE THREAD

**Issue by Vlyan26** [DrOgres/tftloop#33]
The sidebar with the new journals is transparent witch make it unreadable.

FVTT v10.288
System : TFTL 2.0.1

![image](https://user-images.githubusercontent.com/109527072/197332577-a1dba06f-5476-49ce-bf0a-0d5e8567fe5d.png)

culprits :
```css
.sheet.journal-entry {
  background: unset;
  color: black;
}
.sheet.journal-entry .journal-sidebar {
  background: unset;
  color: black;
}
```

so, currently a quick fix to override this is :
```css
.sheet.journal-entry {
  background: url(/ui/denim075.png) repeat;
  color: white;
}
.sheet.journal-entry .journal-sidebar {
  color: white;
}
```

Screen after fix :

![image](https://user-images.githubusercontent.com/109527072/197332672-dde404a3-cdb1-4069-8498-5452b956b07a.png)
